id: 2146b67b54f04d9aa36df076b8fd3db8
initial_creation_type: ocr
source_metadata:
  volumes:
    9b4d5fc02eff45f58a22291e2623b462:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
